version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listalpha-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      # Uncomment and set these values in production
      # - APOLLO_API_KEY=${APOLLO_API_KEY}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    volumes:
      # For development only - remove in production
      - ./public:/app/public
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
